apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-0fc289daa8a194201
  cidr: "172.20.0.0/20"
  subnets:
    public:
      devops-public-subnet-1:
        id: subnet-065bf84762e6aa907
      devops-public-subnet-2:
        id: subnet-05ac0140c073d71c3
    private:
      devops-private-subnet-1:
        id: subnet-0cbd10e65353082d4
      devops-private-subnet-2:
        id: subnet-0f362e09bfd618380

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
